// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using az204quizmasterAPI.Data;

#nullable disable

namespace az204quizmasterAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("az204quizmasterAPI.Models.Entities.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LeftDisplay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QAId")
                        .HasColumnType("int");

                    b.Property<string>("RightDisplay")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QAId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("az204quizmasterAPI.Models.Entities.QA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceLink")
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceLink")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("QAs");
                });

            modelBuilder.Entity("az204quizmasterAPI.Models.Entities.Option", b =>
                {
                    b.HasOne("az204quizmasterAPI.Models.Entities.QA", "QA")
                        .WithMany("Options")
                        .HasForeignKey("QAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QA");
                });

            modelBuilder.Entity("az204quizmasterAPI.Models.Entities.QA", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
